---
title: "national-model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(dplyr)
library(tidyverse)
library(knitr)
library(broom)
library(nnet)
```

```{r data}
data <- read_csv("data/all_national_data_merged.csv")
data <- data %>%
  mutate(Abortion = as.factor(Abortion))
```

```{r }
data <- data %>%
  mutate(MaternalDeaths1216 = case_when(
    !is.na(MaternalDeaths1216) ~ MaternalDeaths1216,
    is.na(MaternalDeaths1216) ~ mean(!is.na(data$MaternalDeaths1216))
  ))
```

```{r pairwise}
ellipse::pairs(Abortion ~ FPNeedMet16 + FPServed16 + FPU20Served16 + FPCenters15 + FPExpend15, 
             data = data, lower.panel = NULL) # FPServed16 & FPU20Served16 + FPServed16&FPCenters15 + FPServed16&FPExpend15
                                              # FPU20Served16&FPCenters15 + FPU20Served16&FPExpend15 + FPCenters15&FPExpend15
ellipse::pairs(Abortion ~ Childcare1213 + PaidLeave14 + ADWaiting16 + ADAdopted16 + ADServed16 + ADPropAdopted16, 
               data = data, lower.panel = NULL) # ADWaiting16&ADAdopted16 + ADWaiting16&ADServed16 + ADAdopted16&ADServed16
ellipse::pairs(Abortion ~ ADPropTerm16 + ParentalLeave + PropUninsured16 + MaternalDeaths1216 + ADWaiting16 + ADAdopted16, 
               data = data, lower.panel = NULL) 
ellipse::pairs(Abortion ~ FPNeedMet16 + FPServed16 + PaidLeave14 + ADWaiting16 + ADPropAdopted16 + MaternalDeaths1216, 
               data = data, lower.panel = NULL)
```

$$
\begin{aligned}
     y_i &= \text{Bernoulli}(p_i)\\
    & logit(p_i/(1-p_i)) \\ &= \beta_0 + \beta_{\text{ needs met}} \text{needs met}_i \\
    &+ \beta_{\text{Clients Served}} \text{Clients Served}_i \\
    &+ \beta_{\text{ Clients Under 20 Served}} \text{ Clients Under 20 Served}_i + \beta_{\text{Family Planning Centers}} \text{ Family Planning Centers}_i \\
    &+ \beta_{\text{Expenditures}} \text{ Expenditures}_i + \beta_{\text{Childcare}} \text{ Childcare}_i\\
    &+ \beta_{\text{Paid Leave}} \text{Paid Leave}_i \\
   &+ \beta_{\text{Waiting for Adoption}} \text{ Waiting for Adoption}_i + \beta_{\text{Adopted}} \text{ Adopted}_i \\
   &+ \beta_{\text{Served}} \text{ Served}_i + \beta_{\text{Proportion of Adoptions}} \text{ Proportion of Adoptions}_i\\
   &+ \beta_{\text{ Proportion of Termination}} \text{ Proportion of Termination}_i
   + \beta_{\text{ Parental Leave}} \text{ Parental Leave}_i\\
   &+ \beta_{\text{Proportion of Uninsured}} \text{ Proportion of Uninsured}_i \\
   &+ \beta_{\text{Maternal Deaths}} \text{ Maternal Deaths}_i \\
   &+ \beta_{\text{Clients Served*Clients Under 20 Served}} \text{ Clients Served}_i* \text {Clients Under 20 Served}_i \\
  &+ \beta_{\text{Clients Served*Family Planning Centers}} \text{ Clients Served}_i* \text {Family Planning Centers}_i \\
  &+ \beta_{\text{Clients Served*Expenditures}} \text{ Clients Served}_i* \text {Expenditures}_i \\
  &+ \beta_{\text{Clients Under 20 Served*Family Planning Centers}} \text{ Clients Under 20 Served}_i* \text {Family Planning Centers}_i \\
  &+ \beta_{\text{Clients Under 20 Served*Expenditures}} \text{ Clients Under 20 Served}_i* \text {Expenditures}_i \\
  &+ \beta_{\text{Family Planning Centers*Expenditures}} \text{ Family Planning Centers}_i* \text {Expenditures}_i \\
  &+ \beta_{\text{Waiting for Adoption*Served}} \text{ Waiting for Adoption}_i* \text {Served}_i \\
  &+ \beta_{\text{Waiting for Adoption*Adopted}} \text{ Waiting for Adoption}_i* \text {Adopted}_i \\
  &+ \beta_{\text{Waiting for Adoption*Adopted}} \text{ Waiting for Adoption}_i* \text {Adopted}_i \\
  &+ \beta_{\text{Served*Adopted}} \text{ Served}_i* \text {Adopted}_i \\
\end{aligned}
$$   

```{r full-model}
full <- multinom(Abortion ~ FPNeedMet16+FPServed16+FPU20Served16+FPCenters15+FPExpend15+
Childcare1213+PaidLeave14+ADWaiting16+ADAdopted16+ADServed16+ADPropAdopted16+ADPropTerm16+ParentalLeave+PropUninsured16+ MaternalDeaths1216 + FPServed16*FPU20Served16 + FPServed16*FPCenters15 + FPServed16*FPExpend15 + 
  FPU20Served16*FPCenters15 + FPU20Served16*FPExpend15 + FPCenters15*FPExpend15 + ADWaiting16*ADAdopted16 + 
  ADWaiting16*ADServed16 + ADAdopted16*ADServed16, data = data)

kable(tidy(full), format = "markdown", digits = 3, caption = "Full Model")
kable(confint(full), format = "markdown", digits = 3, caption = "Full Model Confidence Intervals")

regfit_backward <- step(full, direction = "backward")
```

```{r best-model}
best_model <- multinom(Abortion ~ FPServed16*FPExpend15+MaternalDeaths1216+ADPropTerm16+ParentalLeave+ADAdopted16*ADServed16
                       +Childcare1213+FPNeedMet16+ADWaiting16*ADServed16+ADPropAdopted16+FPU20Served16*FPCenters15+
                         FPServed16*FPCenters15+FPU20Served16*FPExpend15+ADWaiting16*ADAdopted16+FPCenters15*FPExpend15
                       +FPServed16*FPU20Served16+PaidLeave14, data = data)

kable(tidy(best_model), 
      format = "markdown", digits = 3, caption = "Best Model") 
kable(confint(best_model), format = "markdown", digits = 3, caption = "Best Model Confidence Intervals")
```
$$
\begin{aligned}
     y_i &= \text{Bernoulli}(p_i)\\
    & logit(p_i/(1-p_i)) \\ &= \beta_0 + \beta_{\text{ needs met}} \text{needs met}_i \\
    &+ \beta_{\text{Clients Served}} \text{Clients Served}_i \\
    &+ \beta_{\text{ Clients Under 20 Served}} \text{ Clients Under 20 Served}_i + \beta_{\text{Family Planning Centers}} \text{ Family Planning Centers}_i \\
    &+ \beta_{\text{Expenditures}} \text{ Expenditures}_i + \beta_{\text{Childcare}} \text{ Childcare}_i\\
    &+ \beta_{\text{Paid Leave}} \text{Paid Leave}_i \\
   &+ \beta_{\text{Waiting for Adoption}} \text{ Waiting for Adoption}_i + \beta_{\text{Adopted}} \text{ Adopted}_i \\
   &+ \beta_{\text{Served}} \text{ Served}_i + \beta_{\text{Proportion of Adoptions}} \text{ Proportion of Adoptions}_i\\
   &+ \beta_{\text{ Proportion of Termination}} \text{ Proportion of Termination}_i
   + \beta_{\text{ Parental Leave}} \text{ Parental Leave}_i\\
   &+ \beta_{\text{Proportion of Uninsured}} \text{ Proportion of Uninsured}_i \\
   &+ \beta_{\text{Maternal Deaths}} \text{ Maternal Deaths}_i \\
   &+ \beta_{\text{Clients Served*Clients Under 20 Served}} \text{ Clients Served}_i* \text {Clients Under 20 Served}_i \\
  &+ \beta_{\text{Clients Served*Family Planning Centers}} \text{ Clients Served}_i* \text {Family Planning Centers}_i \\
  &+ \beta_{\text{Clients Served*Expenditures}} \text{ Clients Served}_i* \text {Expenditures}_i \\
  &+ \beta_{\text{Clients Under 20 Served*Family Planning Centers}} \text{ Clients Under 20 Served}_i* \text {Family Planning Centers}_i \\
  &+ \beta_{\text{Clients Under 20 Served*Expenditures}} \text{ Clients Under 20 Served}_i* \text {Expenditures}_i \\
  &+ \beta_{\text{Family Planning Centers*Expenditures}} \text{ Family Planning Centers}_i* \text {Expenditures}_i \\
  &+ \beta_{\text{Waiting for Adoption*Served}} \text{ Waiting for Adoption}_i* \text {Served}_i \\
  &+ \beta_{\text{Waiting for Adoption*Adopted}} \text{ Waiting for Adoption}_i* \text {Adopted}_i \\
  &+ \beta_{\text{Served*Adopted}} \text{ Served}_i* \text {Adopted}_i \\
\end{aligned}
$$   

```{r pred}
# prediction of model
pred <- predict(best_model, type = "class")
table <- table(na.omit(data)$Abortion, pred)
confusion_matrix <- as.data.frame(table)

ggplot(data = confusion_matrix,
       mapping = aes(x = Var1,
                     y = pred)) +
  geom_tile(aes(fill = Freq)) +
  geom_text(aes(label = sprintf("%1.0f", Freq)), vjust = 1) +
  scale_fill_gradient(low = "blue",
                      high = "red",
                      trans = "log")
```

